[package]
edition = "2021"
name = "cache-scratch"
publish = false
version = "0.0.0"

[profile.release]
codegen-units = 1
lto = true

[dependencies]
allocator = { path = "../../allocator" }
common = { path = "../common" }
